# Generated by Django 4.1.1 on 2022-09-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=50, verbose_name="Ник")),
                ("mail", models.EmailField(max_length=254, verbose_name="Email")),
                ("stars", models.PositiveIntegerField(verbose_name="Звёзды")),
                (
                    "review",
                    models.TextField(max_length=500, verbose_name="Опыт использования"),
                ),
            ],
        ),
    ]
