# Generated by Django 4.1.1 on 2022-10-02 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Specializations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, verbose_name="Специализация ресторана"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Restaurants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                ("address", models.CharField(max_length=150, verbose_name="Адрес")),
                ("site", models.CharField(max_length=100, verbose_name="Веб-сайт")),
                (
                    "contacts",
                    models.CharField(max_length=15, verbose_name="Контактный телефон"),
                ),
                (
                    "specialization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="restaurants.specializations",
                    ),
                ),
            ],
        ),
    ]
