# Для примера взял несколько цветов
COLORS = [
    "Red",
    "Grey",
    "Light blue",
    "Dark Blue",
    "Green",
    "Yellow",
    "Pink",
    "Orange",
    "Brown",
    "White",
    "Black",
    "Violet",
    "Gold",
    "Silver",
    "Amber",
    "Azure",
    "Beige",
    "Body color",
    "Bronze",
    "Chocolate",
    "Coral",
    "Denim blue",
    "Lilac",
    "Pearl",
    "Raspberry",
    "Sand",
    "Snow",
    "Vinous",
    "Light sea green",
]