# Generated by Django 4.1.1 on 2022-09-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Human",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=50, verbose_name="Фамилия")),
                ("age", models.PositiveSmallIntegerField(verbose_name="Возраст")),
                (
                    "gender",
                    models.CharField(
                        choices=[("М", "Мужской"), ("Ж", "Женский")], max_length=2
                    ),
                ),
            ],
            options={
                "verbose_name": "Человек",
                "verbose_name_plural": "Люди",
            },
        ),
    ]
