# Generated by Django 4.1.1 on 2022-09-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_2", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="сritique",
            name="spoilers",
            field=models.BooleanField(default=False, verbose_name="Содержит спойлеры?"),
        ),
    ]
