# Generated by Django 4.1.2 on 2022-10-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WaterOrders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=50, verbose_name="Фамилия")),
                ("e_mail", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "contacts",
                    models.CharField(max_length=12, verbose_name="Контактный телефон"),
                ),
                ("address", models.CharField(max_length=100, verbose_name="Адрес")),
                (
                    "months_of_delivery",
                    models.CharField(
                        choices=[
                            (1, "1 месяц"),
                            (3, "3 месяца"),
                            (6, "6 месяцев"),
                            (12, "12 месяцев"),
                        ],
                        max_length=2,
                        verbose_name="Срок месяцев доставки",
                    ),
                ),
                (
                    "bottle_volume",
                    models.CharField(max_length=2, verbose_name="Объём баллона воды"),
                ),
            ],
        ),
    ]
