# Generated by Django 4.1.2 on 2022-10-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waterorders",
            name="bottle_volume",
            field=models.CharField(
                choices=[("5", "5 литров"), ("10", "10 литров"), ("15", "15 литров")],
                max_length=2,
                verbose_name="Объём баллона воды",
            ),
        ),
        migrations.AlterField(
            model_name="waterorders",
            name="months_of_delivery",
            field=models.CharField(
                choices=[
                    ("1", "1 месяц"),
                    ("3", "3 месяца"),
                    ("6", "6 месяцев"),
                    ("12", "12 месяцев"),
                ],
                max_length=2,
                verbose_name="Срок месяцев доставки",
            ),
        ),
    ]
