# https://www.homeenglish.ru/otherfootwear.htm
SHOES = [
    "Apres-ski",
    "Ballet flats",
    "Dolly shoes",
    "Waders",
    "Combat boots",
    "(heel-strap) Sandals",
    "Open-toe sandals",
    "Boots",
    "High shoes",
    "High overshoes",
    "Hessian",
    "Brogues",
    "Football boots",
    "Cleats",
    "Soccer shoes",
    "Valenki",
    "Felt boots",
    "Waraji",
    "Trekking boots",
    "Flip-flops",
    "Thongs",
    "Japanese sandals",
    "Jandals",
    "Galoshes",
    "Boat shoes",
    "Dickersons",
    "Overshoes",
    "Geta",
    "Derby",
    "Gibson",
    "Bucks",
    "Keds",
    "Cowboy boots",
    "Athletic shoe",
    "Bast shoes",
    "Slip-ons shoes",
    "Moccasins",
    "Monquis",
    "Oxford shoes",
    "Bootee",
    "Bootie",
    "Walking shoes",
    "Low shoes",
    "Pointe shoe",
    "Crakows",
    "Crackowes",
    "Wellington boot",
    "Rubber-boots",
    "Wellies",
    "Wellingtons",
    "Clog",
    "Sandals",
    "Boots",
    "Slippers",
    "Houseshoes",
    "Dress shoe",
    "Mukluks",
    "Kamik",
    "Bedroom slippers",
    "(lace-up) Shoes",
]
